### PR TITLE
Downloading the meetup data into a file for more details

### PR DESCRIPTION
**Pull request by mmanrique**
- I'm creating a new file under _data/results.json (ignored). This file will contain all the meetup data downloaded from the API.
- I'm using Jekyll Generator to pull data from meetup api into the site.
- This data is pulled only once, allowing for developer live-refresh to be much faster, having only to pull it the first time.
- I'm creating a new view for each Community row. This view now includes a link, tooltip and member count.
- All of this data is pulled from the file mentioned above.
- The tooltip pulls the description, a thumbnail image if available and the member count from meetup api.
- If the community is not a meetup community, only the link is displayed.

Here is the current view

Screen Shot 2019-10-08 at 4 08 41 PM

Here is an example of the tooltip 
Screen Shot 2019-10-08 at 4 09 22 PM

Here is another example 
Screen Shot 2019-10-08 at 4 10 16 PM

Here is group that does not have a thumblink
Screen Shot 2019-10-08 at 4 11 04 PM

Here is a non-meetup group
Screen Shot 2019-10-08 at 4 11 44 PM

### CODE REVIEW

**Comment by joelibaceta** [comment]
Yeah!,

But I have a doubt, you need results file to make easier the frontend development time?.

**Comment by joelibaceta** [comment]
@darksy12 what do you think? Its looks good :)

**Comment by mmanrique** [comment]
Before when starting `bundle exec jekyll server` it will pull the data from the meetup API, and it will pull the api data each time code changes were made.

With the inclusion of a results.json file acting as resource file in a cache-like fashion , code changes will no longer trigger a _Full data reload_ but only update the html content.

**Comment by joelibaceta** [comment]
Thanks for your contribution 👍

**Comment by joelibaceta** [comment]
@mmanrique Why do you choose truncate the content? maybe cool be better a full text description.

Captura de Pantalla 2019-10-08 a la(s) 22 08 37

I could suggest a close button too.

Ideas for the next PR 👍

**Comment by mmanrique** [comment]
Some sites may contain a very long description causing it to block a lot of the other communities in the list.
Screen Shot 2019-10-08 at 8 14 06 PM

Can be updated by removing the 'truncate' class though.
Glad to help

**Comment by darksy12** [comment]
@mmanrique Great PR! Looks good. I think truncating it is a good choice tbh

**Comment by joelibaceta** [comment]
@darksy12 @mmanrique maybe a partial truncate ? 3 o 5 lines are good enough

**Pull request merged**
