### PR TITLE
Using badges instead of plain text

### PR DESCRIPTION
**Pull request by mmanrique**
Since the label is doing nothing. I decided to include badges that look much better

### CODE REVIEW

**Comment by darksy12** [comment]
@joelibaceta @hpneo @07Gond Como lo ven?

**Comment by joelibaceta** [comment]
@mmanrique  podrías generar un gh-pages en el fork o pasarnos un screenshot para ver como quedaría ?

**Comment by mmanrique** [comment]
Current: [
Screen Shot 2019-10-07 at 4 10 01 PM
](url)

**Comment by mmanrique** [comment]
New: 
Screen Shot 2019-10-07 at 4 09 51 PM

**Comment by joelibaceta** [comment]
Agree :D

**Review by joelibaceta — APPROVED** [review]

**Comment by joelibaceta** [comment]
@darksy12 merge 👍

**Pull request merged**
