### PR TITLE
Adding "Proximos Eventos" column

### PR DESCRIPTION
**Pull request by mmanrique**
- I created a simple app that pulls the information from the communities and aggregates the next events from all of them.
- You can see the code in here: https://github.com/mmanrique/community-event-aggregator 
- the endpoint is http://community-event-aggregator.herokuapp.com/
- it will copy the information provided by meetup api.
- This PR includes the intial draft (I'm no UI designer) of the "Proximos Eventos" Column.
- I added a flag in the config file to dial it up or down.

I also added a sample.json file that contains a snapshot of the meetup information for development purposes.

The problem with Heroku is that my app is idle and also it is calling the meetup api per request, causing it to take around 3 seconds to gather the information. In the future days I will focus on caching mechanism and timely pulling.

Here are some pictures

While loading

Screen Shot 2019-10-09 at 4 23 27 PM

Loaded

Screen Shot 2019-10-09 at 4 22 46 PM

The experience is not the best and it would probably be best to truncate the event name.

I'm including moment.js library for date manipulation.

### CODE REVIEW

**Comment by mmanrique** [comment]
This is related to this issue: https://github.com/peruanosdev/peruanos.github.io/issues/7

**Comment by joelibaceta** [comment]
@mmanrique maybe could you user word wrap to make a multiline title

**Comment by joelibaceta** [comment]
@mmanrique could we group by days? to build a prettier view ? something like the image in the issue.

**Comment by mmanrique** [comment]
I updated the heroku app to group by dates.
This is how it looks now.
Screen Shot 2019-10-10 at 1 16 35 PM

As I said, I'm no designer and don't know how to render calendar images, but it would be nice if we could use images instead of the text. But that's a start.

Also, the heroku app is slow and needs to have caching mechanisms

This is how the mobile version looks like
Screen Shot 2019-10-10 at 1 19 21 PM

**Comment by joelibaceta** [comment]
@mmanrique why do you choose get events using JS ? maybe could be better get events in the building time using ruby https://api.meetup.com/[COMMINITY]/events.

**Comment by mmanrique** [comment]
Then the list would be static and it would have to be rebuilt in order to be updated. I'm also considering this by having a bot push to the repo every day. Don't you think?

**Comment by joelibaceta** [comment]
@mmanrique we have a cron to rebuild every night

**Comment by joelibaceta** [comment]
@mmanrique give a couple of hours, I'm trying to refactor all the code to maintain an easy-to-read and readable code.

**Comment by mmanrique** [comment]
Ok, I did not know that. I will work to make it into a Ruby script.
Can you point me into this "cron to rebuiild".
Thanks

**Pull request merged**
